### ISSUE TITLE
Autocomplete crashes ST3

### ISSUE THREAD

**Issue by troymcginnis** [kallookoo/sublime-text-wordpress#1]
Hey!

It seems that whenever I use Wordpress Completions to try to autocomplete _any_ WordPress function, it causes my Sublime Text 3 to crash. I'm running Sublime Text 3, build 3126 stable on OSX 10.11.6.

Let me know what information you need from me or how I can help troubleshoot the issue.

Thanks!

**Comment by kallookoo** [comment]
Hi, @troymcginnis 
Please disabled all packages do not come by default in the application to see if this package really is the culprit.
This packages only uses *.sublime-(completions|snippet) files without append any class or function inside of program.
If after to try only with this package crashed this program, tell me exactly what function is for check in my system and append output console error.

**Comment by kallookoo** [comment]
Closed, because not any respond.
