### ISSUE TITLE
Feature request - package option to remove ';'

### ISSUE THREAD

**Issue by alfaex** [kallookoo/sublime-text-wordpress#3]
First, awesome plugin, thanks a lot.

Every time that i use the auto-completion it puts an ';' at the end.

it would be nice to have a option on the plugin like 
{
    "auto_completion_end_semicolon": true/false
}

**Comment by kallookoo** [comment]
In some cases within the functions is optional, the last step removes the ';'.

The plugin uses the sublime-completions files, for the moment it will remain so, although I am thinking of using on_query_completions, to be able to decide whether to show what is cataloged as private or to discard plugins and themes that a user would not use.
