### ISSUE TITLE
can`t to find it in sublime 3 (doesn`t exist)

### ISSUE THREAD

**Issue by UriShlomov** [kallookoo/sublime-text-wordpress#4]
I can not to find it inside sublime 3 (does not exist)

**Comment by kallookoo** [comment]
I can explain it better.
I have deleted the package to search and install it and I have not had any problems.
Note: The package name is WordPress Completions

**Comment by kallookoo** [comment]
Close beacause not respond

**Comment by benbodhi** [comment]
Hey I don't mean to re-open an old thread, but I don't see it in Package Control search.
https://www.dropbox.com/s/zl83fr6ubool9yq/Screenshot%202018-09-04%2016.31.19.png?dl=0

**Comment by harryqt** [comment]
He is actually right, does not show up in Package Control in Sublime 3

**Comment by kallookoo** [comment]
Hi, @Dibbyo456 this is one bug on Package Control.
See https://github.com/wbond/package_control/issues/1379
