### ISSUE TITLE
None of the hints are working

### ISSUE THREAD

**Issue by benbodhi** [kallookoo/sublime-text-wordpress#5]
Hi there,
Your package was working fine when I first installed it a while ago. Now it doesn't seem to work and I don't know why.
I removed the package then reinstalled it, but same thing.

For example, if I type `wp-` or `WP-` nothing shows up as a prompt like it used to.
If I type `wp-pluginHeader` and press return/enter, the header block isn't output.

Not sure how to even troubleshoot it unfortunately.

**Comment by kallookoo** [comment]
Hi @benbodhi 
What is your version of Sublime Text and OS?

The `wp-pluginHeader` snippet not exits is `wp-plugin-header` because of limitations of the Sublime Text by default on empty file not open completions popup, try use `ctrl+space` o `alt+\` (Linux)

If I have noticed what you say in another message (deleted) that the Sublime Text (Package Control) sometimes adds the package to the list of the ignored packages.
I will create an issue to be solved since the error is very big.

**Comment by benbodhi** [comment]
Hi,
I'm running Sublime Text 3.1.1 build 3176 on Mac OS High Sierra - 10.13.6.

My original deleted message is irrelevant, it wasn't showing up in package installer because it was already installed. I removed it, then it did show up again, and I installed again successfully. So I deleted my message because it works.

The completions pop up is the issue. It doesn't show. But as you said, it doesn't work on empty files. I saved a file and tested it, and it works fine. I figured it would work on blank files since when you start a plugin and need a plugin header, you'd likely be using a new empty file.

Is there some way to make the completions pop up on empty files?

**Comment by kallookoo** [comment]
When there is empty file, the default syntax is plain text.
Only wp-plugin-readme works and only after press ctrl+space, Everything else works when the syntax is PHP, and if there is empty file you need to use ctrl+space to show the popup. 
Limitation or advantage of how the Sublime Text shows the popup.

I do not overload the Sublime Text of snippets adjust the triggers according to the context.
A PHP function is needed if the syntax is PHP, not CSS, JS, etc ...
Imagine that there were about 1000 snippets and they are all shown in all contexts, it does not make sense.

summarizing:
- Plain text syntax only wp-plugin-readme after ctrl+space.
- PHP syntax everything else, and some need ctrl+space.

**Comment by benbodhi** [comment]
That makes perfect sense, thank you!
I’ll try ctrl+space when I’m back in the computer.
