### ISSUE TITLE
wp-taxonomy autocompletion is not working for me

### ISSUE THREAD

**Issue by alexkuc** [kallookoo/sublime-text-wordpress#6]
Hello!

I am on OSX 10.13.6 with ST3 (3.2.1) installed WordPress Completions through Package Control. Everything appears to work fine _except_ for `wp-taxonomy` autocompletion:

![broken](https://user-images.githubusercontent.com/3331946/58382689-f82d7100-7fd5-11e9-91e6-f3b9a835fe91.gif)

Other completions appears to work fine:

![working](https://user-images.githubusercontent.com/3331946/58382681-e21fb080-7fd5-11e9-8f84-eb203e1f8de7.gif)

**Comment by kallookoo** [comment]
Hi @alexkuc 
Thanks for reporting, and create a new version resolving it.
